spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true 
    
cloud:
  aws:
    credentials:
      useDefaultAwsCredentialsChain: true
    region:
      static: ap-northeast-1

memcached:
  cache: 
    servers: 192.168.33.10:11211 
    mode: static
    expiration: 600
    protocol: binary
